version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: isaid
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - ./database_backup.sql:/docker-entrypoint-initdb.d/database_backup.sql
    ports:
      - "5433:5432"
    networks:
      - backend

  app:
    build:
      context: .  # Builds the image from the Dockerfile in the current directory
    ports:
      - "8000:80"
    environment:  
      DB_USER: postgres
      DB_PASSWORD: dbpassword
      DB_HOST: db  # Refers to the 'db' service defined in the same file
      DB_PORT: 5432
      DB_NAME: isaid
    networks:
      - backend

networks:
  backend:
    driver: bridge
